# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.on-demand-completion]
local = "~/dotfiles/plugins/on-demand-completion"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# =====================
# Zsh Plugins
# =====================

[plugins.compinit]
# inline = 'autoload -Uz compinit && zsh-defer compinit'

# from https://gist.github.com/ctechols/ca1035271ad134841284
inline = '''
_compinit() {
  local re_initialize=0
  for match in .zcompdump*(.Nmh+24); do
    re_initialize=1
    break
  done

  autoload -Uz compinit
  if [ "$re_initialize" -eq "1" ]; then
    compinit
    # update the timestamp on compdump file
    compdump
  else
    # omit the check for new functions since we updated today
    compinit -C
  fi
}
_compinit
'''

[plugins.dircolors-solarized-zsh]
github = 'pinelibg/dircolors-solarized-zsh'
hooks.post = 'export DIRCOLORS_SOLARIZED_ZSH_THEME="ansi-dark"'
apply = ['defer']

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.ni-zsh]
github = 'azu/ni.zsh'
apply = ['defer']

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'
apply = ['defer']

# [plugins.zsh-iterm2]
# github = 'laggardkernel/zsh-iterm2'
# apply = ['defer']
# use = ['init.zsh']

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
# apply = ["defer"]

# Reminder機能を使いたいのでこっちにする
[plugins.zsh-abbr]
github = 'olets/zsh-abbr'
hooks.post = '''
ABBR_USER_ABBREVIATIONS_FILE="${DOTFILES_DIR}/config/zsh-abbr/user-abbreviations"
ABBR_GET_AVAILABLE_ABBREVIATION=1
ABBR_LOG_AVAILABLE_ABBREVIATION=1
ABBR_AUTOLOAD=0

abbr load
'''

# =====================
# aliases
# =====================

# https://kapeli.com/cheat_sheets/Oh-My-Zsh_Git.docset/Contents/Resources/Documents/index

[plugins.git-alias-fn]
local = '~/dotfiles/plugins/ohmyzsh-git-fn'
apply = ['defer']

# =====================
# tools from aqua activation
# =====================

# aquaよりも先にmiseを有効化
# https://aquaproj.github.io/docs/reference/use-aqua-with-other-tools
[plugins.mise]
inline = '''
# Node.jsのインストール後にcorepack enableを自動でやる
export MISE_NODE_COREPACK=1
# Node.jsのインストール後に自動でインストールするパッケージを指定するファイルのパスを指定
export MISE_NODE_DEFAULT_PACKAGES_FILE="${DOTFILES_DIR}/config/mise/.default-npm-packages"

eval "$(~/.local/bin/mise activate zsh)"
on_demand_completion "mise"
'''

[plugins.aqua]
inline = '''
export AQUA_GLOBAL_CONFIG="${DOTFILES_DIR}/config/aqua.yaml"
export AQUA_POLICY_CONFIG="${DOTFILES_DIR}/config/aqua/aqua-policy.yaml"
export PATH="$(aqua root-dir)/bin:$PATH"
on_demand_completion "aqua"
'''

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

# =====================
# Completion of external commands
# =====================

[plugins.arduino-cli-completion]
inline = 'on_demand_completion "arduino-cli"'

[plugins.docker-completion]
inline = 'on_demand_completion "docker"'

[plugins.deno-completion]
inline = 'on_demand_completion "deno" "deno completions zsh"'

[plugins.ast-grep-completion]
inline = 'on_demand_completion "sg" "sg completions zsh"'

[plugins.yq-completion]
inline = 'on_demand_completion "yq" "yq shell-completion zsh"'

[plugins.gh-completion]
inline = 'on_demand_completion "gh" "gh completion -s zsh"'

[plugins.pnpm-completion]
inline = 'on_demand_completion "pnpm" "pnpm completion zsh"'

[plugins.pnpm-shell-completion]
inline = '''
# インストール自体はaquaで行う
local plugin_path_dir=$(dirname $(aqua which pnpm-shell-completion))
local plugin_path="${plugin_path_dir}/pnpm-shell-completion.plugin.zsh"
source $plugin_path
'''

[plugins.zsh-better-npm-completion]
github = 'lukechilds/zsh-better-npm-completion'
# apply = ['defer']
hooks.post = '''
# required:  zsh-better-npm-completion
# original: https://github.com/lukechilds/zsh-better-npm-completion/blob/master/zsh-better-npm-completion.plugin.zsh

_zbnc_zsh_better_ni_completion() {
  # Store custom completion status
  local custom_completion=false

  # Load custom completion commands
  case "$(_zbnc_npm_command)" in
    add)
      _zbnc_npm_install_completion
      ;;
    remove)
      _zbnc_npm_uninstall_completion
      ;;
    run)
      _zbnc_npm_run_completion
      ;;
  esac

  # Fall back to default completion if we haven't done a custom one
  [[ $custom_completion = false ]] && _zbnc_default_npm_completion
}

zsh-defer compdef _zbnc_zsh_better_ni_completion ni
'''


# =====================
# additional zshrc
# =====================

[plugins.local-zsh]
inline = 'source ${DOTFILES_DIR}/.zshrc.local'
