# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
hooks.post = '''
zsh-defer source $ZSHRC_DIR/lazy.zsh
zsh-defer -t 0.001 autoload -Uz compinit
zsh-defer -t 0.001 compinit
'''

[plugins.dircolors-solarized-zsh]
github = 'pinelibg/dircolors-solarized-zsh'
hooks.post = 'export DIRCOLORS_SOLARIZED_ZSH_THEME="ansi-dark"'
apply = ['defer']

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.ni-zsh]
github = 'azu/ni.zsh'
apply = ['defer']

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'
apply = ['defer']

[plugins.zsh-iterm2]
github = 'laggardkernel/zsh-iterm2'
apply = ['defer']
use = ['init.zsh']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ["defer"]
