[tool_alias]
gdn = "github:elecdeer/git-gardener"

[tools]
1password = "2.34.1"
"aqua:boyter/scc" = "3.7.0"
"aqua:docker/buildx" = "0.35.0"
"aqua:docker/cli" = "29.6.0"
"aqua:docker/compose" = "5.2.0"
"aqua:g-plane/pnpm-shell-completion" = "0.5.5"
"aqua:k1LoW/gh-do" = "0.6.0"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/pastel" = "0.12.0"
"aqua:ymtdzzz/otel-tui" = "0.7.3"
ast-grep = "0.44.0"
bat = "0.26.1"
bun = "1.3.14"
chezmoi = "2.70.5"
colima = "0.10.3"
delta = "0.19.2"
deno = "2.8.3"
dive = "0.13.1"
fd = "10.4.2"
fzf = "0.73.1"
gh = "2.95.0"
ghq = "1.10.1"
# https://github.com/k1LoW/git-wt/pull/162
"github:k1LoW/git-wt" = "0.29.0"
gdn = { version = "0.3.2", bin = "gdn" }
"github:trasta298/keifu" = "0.5.0"
"github:zyedidia/micro" = "2.0.15"
"github:pnpm/pnpm" = "11.9.0"
hyperfine = "1.20.0"
jq = "1.8.2"
lima = "2.1.3"
lsd = "1.2.0"
node = "26.4.0"
"npm:@mizchi/lsmcp" = "0.10.0"
"npm:ccusage" = "20.0.14"
"npm:typescript" = "6.0.3"
"npm:typescript-language-server" = "5.3.0"
pinact = "4.1.0"
ripgrep = "15.1.0"
usage = "3.5.3"
yq = "4.53.3"
"npm:oxfmt" = "0.56.0"
"npm:@playwright/cli" = "0.1.14"
go = "1.26.4"
cloudflared = "2026.6.1"
zellij = "0.44.3"
viteplus = "latest"
"aqua:codeberg.org/mergiraf/mergiraf" = "0.17.0"
"github:babarot/gomi" = "latest"
wrangler = "latest"
rtk = "0.42.4"
