---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.300.2 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: aqua/registry.yaml
packages:
  - name: cli/cli@v2.65.0
  - name: sharkdp/bat@v0.25.0
  - name: lsd-rs/lsd@v1.1.5
  - name: sharkdp/fd@v10.2.0
  - name: BurntSushi/ripgrep@14.1.1
  - name: dandavison/delta@0.18.2
  - name: sharkdp/pastel@v0.10.0
  - name: jqlang/jq@jq-1.7.1
  - name: mikefarah/yq@v4.45.1
  - name: zyedidia/micro@v2.0.14
  - name: ast-grep/ast-grep@0.34.1
  - name: junegunn/fzf@v0.58.0
  - name: starship/starship@v1.22.1
  - name: sharkdp/hyperfine@v1.19.0
  - name: boyter/scc@v3.4.0
  - name: k1LoW/gh-do@v0.5.2
  - name: g-plane/pnpm-shell-completion@v0.5.4
  - name: abiosoft/colima@v0.8.1
  - name: lima-vm/lima@v1.0.4
