---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.192.0 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: aqua/registry.yaml
packages:
  - name: cli/cli@v2.50.0
  - name: sharkdp/bat@v0.24.0
  - name: lsd-rs/lsd@v1.1.2
  - name: sharkdp/fd@v10.1.0
  - name: BurntSushi/ripgrep@14.1.0
  - name: dandavison/delta@0.17.0
  - name: sharkdp/pastel@v0.9.0
  - name: jqlang/jq@jq-1.7.1
  - name: mikefarah/yq@v4.44.1
  - name: zyedidia/micro@v2.0.13
  - name: ast-grep/ast-grep@0.22.6
  - name: junegunn/fzf@0.53.0
  - name: starship/starship@v1.19.0
  - name: sharkdp/hyperfine@v1.18.0
  - name: boyter/scc@v3.3.4
  - name: k1LoW/gh-do@v0.5.0
  - name: g-plane/pnpm-shell-completion@v0.3.0
    registry: local
