---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.161.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.47.0
  - name: jdx/mise@v2024.4.4
  - name: sharkdp/bat@v0.24.0
  - name: lsd-rs/lsd@v1.1.2
  - name: sharkdp/fd@v9.0.0
  - name: BurntSushi/ripgrep@14.1.0
  - name: dandavison/delta@0.17.0
  - name: sharkdp/pastel@v0.9.0
  - name: jqlang/jq@jq-1.7.1
  - name: mikefarah/yq@v4.43.1
  - name: zyedidia/micro@v2.0.13
  - name: ast-grep/ast-grep@0.20.5
  - name: junegunn/fzf@0.49.0
  - name: starship/starship@v1.18.2
  - name: sharkdp/hyperfine@v1.18.0
