#!/usr/bin/env zsh

local ghq_root="${1:-$(ghq root)}"

while IFS= read -r repo; do
  [[ -z "$repo" ]] && continue

  local repo_path="$ghq_root/$repo"
  local git_time_info mtime relative_time

  git_time_info=$(git -C "$repo_path" log -1 --format=$'%ct\t%cr' HEAD 2>/dev/null)
  if [[ -z "$git_time_info" ]]; then
    continue
  fi

  mtime=${git_time_info%%$'\t'*}
  relative_time=${git_time_info#*$'\t'}

  printf "%s\t%s\t%-60s\t\033[2m%s\033[0m\n" "$mtime" "$repo" "$repo" "$relative_time"
done < <(ghq list) | sort -t $'\t' -k1 -rn